#cloud-config

hostname: rancher

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTqJS1AqRKQW3Paez7lzti/RW94YYesUKRmN3JRx3mHifoLjezxh1eN++mPAXnBG0fMwAkiOC4vyWgQEZDZQjn2V2ZTkefztUxLIcfn7OY7sU9ivdftthByyQQ8f06UmXfgiOl0d5Nm+2Dy9gr4Vd5JhtdlYCe4xI+X998Lcgbil0wG/WyTfXhwyXB+K5l5CJmqSr1HluAfd6YNO7tK4KgaHcv7PODRmy4E9jvZ/jFOSU4MRL30p9LgN2qjMhmJQM92fpen7p/EBSk3m21GuB4y+K5SGGIjPiS5eXampnV2pBvxS6uT/puQD69ZyTn1rpl1KLpnJEH1/BWSrhqhRdKbdkLlSufadYrE19k+C/4qZSOTiyKRzKGMWDQduA1WZxcUdxh2N5jqG47zIDsEwfcAPA/eMe5z14lH8nHYIFy4cReTvRcz6d9ttntp+CAYPTxVrbgRWFu6gaLgjNcj/lkcTNFOG4VYo7q6SNhoCXD8WETx2END+Pz3LpB9TATCwk= huaweipsmart
